Replace perl template with custom script
quictls/quictls pull request #166
Opened 2024-12-20 21:38 UTC by richsalz

oof. The comment in build.conf about the comlexity of the script in `Configurations/unix-Makefile.tmpl` literally cost me days (elapsed time) of trying to make this work.

ANYHOW, with this PR, we are down to a dozen templated `.in` files, compared to 151 in openssl. Assuming the builds work, I think we're ready to take `cmake`

## Checklist
Thank you for your contribution. Please answer the following:

- [ ] I acknowledge that I am authorized to submit this code under
the terms of the [Apache License](https://www.apache.org/licenses/LICENSE-2.0)
- [ ] All new public APIs are documented
- [ ] All new public functions have tests
- [ ] All new public functions have fuzzing tests

2025-01-04 22:18 UTC, botovq approved these changes
Looks good, but it's all just chicken scratches to me.

2025-01-04 22:18 UTC, botovq commented on include/mkhdr.pl
> +# Copyright 2024 The QuicSSL Project Authors. All Rights Reserved.
```suggestion
# Copyright 2024 The QuicTLS Project Authors. All Rights Reserved.
```

2025-01-04 22:18 UTC, botovq commented on include/openssl/asn1.h.gen
```suggestion
```
Delete extra line

2025-01-04 22:18 UTC, botovq commented on include/openssl/asn1t.h.gen
```suggestion
```
delete extra blank line

2025-01-04 22:21 UTC, botovq requested changes
I meant to request changes.

2025-01-04 23:05 UTC, richsalz commented
Merged your changes.  Will wait to make sure it didn't break anything :)

2025-01-04 23:10 UTC, botovq submitted a review, later dismissed
You never know...

Reminds me of an issue we had (in flex, IIRC) where an extra blank line would result in an indentation change triggering `-Wmisleading-indentation`.

2025-01-04 23:10 UTC, botovq commented
Hrm there's a conflict.

2025-01-05 00:01 UTC, richsalz commented
#165 removed lines from err.h, I'll fix/rebase now.

2025-01-05 00:03 UTC, richsalz commented
There wasn't a conflict, just that the github web interface can't deal with things when a file gets renamed.

2025-01-05 07:32 UTC, botovq approved these changes

2025-01-05 07:32 UTC, merged