Remove some single-use header files
quictls/quictls pull request #182
Opened 2024-12-28 18:41 UTC by richsalz

Did not remove all, some are either very big test data or otherwise generated.

## Checklist
Thank you for your contribution. Please answer the following:

- [X] I acknowledge that I am authorized to submit this code under
the terms of the [Apache License](https://www.apache.org/licenses/LICENSE-2.0)
- [ ] All new public APIs are documented
- [ ] All new public functions have tests
- [ ] All new public functions have fuzzing tests

2024-12-28 18:41 UTC, richsalz commented
As promised in https://github.com/quictls/quictls/pull/180#issuecomment-2564341868

2024-12-28 18:52 UTC, botovq commented
You can't remove the public `ecdh.h`, `ecdsa.h` and `ossl_typ.h` headers. Things still use them. For example see [codesearch for ecdsa.h](https://codesearch.debian.net/search?q=openssl%2Fecdsa.h&literal=1).

2024-12-28 21:37 UTC, richsalz commented
Restored those files.  I promise to use codesearch next time before I remove something :)

2025-01-02 16:49 UTC, botovq requested changes
Some mumblings and one or two nits.

2025-01-02 16:49 UTC, botovq commented on include/apps/testkeys.h
> +static unsigned char dsa512_priv[] = {
All these constants should really be const and have no business being in a header.

2025-01-02 16:49 UTC, botovq commented on include/apps/testkeys.h
> +
The copyright notice below should be removed.

2025-01-02 16:56 UTC, richsalz commented on include/apps/testkeys.h
> +static unsigned char dsa512_priv[] = {
Yeah.  Would it be better if I called it `testkeys.inc` ?

2025-01-02 16:59 UTC, richsalz commented on include/apps/testkeys.h
> +static unsigned char dsa512_priv[] = {
I moved `include/apps/testkeys.h` to 'apps/testkeys.inc'

2025-01-02 16:59 UTC, botovq commented on include/apps/testkeys.h
> +static unsigned char dsa512_priv[] = {
I'd just add a testkeys.c file with a sane api and provide the prototypes either in speed.c (the only consumers) or apps.h. I can make a PR once this is merged.

2025-01-02 17:03 UTC, richsalz commented on apps/speed.c
> +    } while (0)
Added #191

2025-01-02 17:04 UTC, richsalz commented
fixup pushed

2025-01-02 17:12 UTC, botovq approved these changes

2025-01-02 17:13 UTC, merged

2025-01-02 17:13 UTC, richsalz commented
@botovq tag, you're it :)