Rm trace
quictls/quictls pull request #184
Opened 2024-12-28 22:10 UTC by richsalz

## Checklist
Thank you for your contribution. Please answer the following:

- [x] I acknowledge that I am authorized to submit this code under
the terms of the [Apache License](https://www.apache.org/licenses/LICENSE-2.0)
- [ ] All new public APIs are documented
- [ ] All new public functions have tests
- [ ] All new public functions have fuzzing tests

2025-01-02 23:42 UTC, botovq reviewed
I haven't read much of this, but here's a couple of comments.

2025-01-02 23:48 UTC, richsalz commented on apps/lib/http_server.c
> +                    trace_log_message(OSSL_TRACE_CATEGORY_HTTP, prog,
merged this, adding the printf attribute in a second.

2025-01-05 08:25 UTC, botovq commented
Don't forget to remove the things added by the keylog PR

2025-01-05 12:01 UTC, botovq commented on crypto/provider_conf.c
```suggestion
```

2025-01-05 12:01 UTC, botovq commented on crypto/provider_conf.c
```suggestion
```

2025-01-05 12:04 UTC, botovq commented on crypto/provider_conf.c
>  void ossl_provider_add_conf_module(void)
Oh, lovely. So they added more layers to the conf mess. Just one or two layers more and it will be glorious.

2025-01-05 12:08 UTC, botovq commented on include/openssl/configuration.h.in
> +# ifdef OPENSSL_NO_TRACE
```suggestion
# ifndef OPENSSL_NO_TRACE
```

2025-01-05 12:08 UTC, botovq commented on include/openssl/configuration.h.in
> +# ifdef OPENSSL_NO_TLS1_3
```suggestion
# ifndef OPENSSL_NO_TLS1_3
```

2025-01-05 12:15 UTC, botovq commented on util/check-format.pl
> +            report("code after '}'") unless $tail eq "" || $tail =~ m/(else|while|$)/;
Not sure, but should that not be 
```suggestion
            report("code after '}'") unless $tail eq "" || $tail =~ m/(else|while)(\W|$)/;
```
to ensure that there's a word boundary after while and else?

2025-01-05 13:42 UTC, richsalz commented on crypto/asn1/tasn_utl.c
>          REF_ASSERT_ISNT(ret < 0);
I did this in my early days of OpenSSL, and yes, it was because I was learning to get `OPENSSL_NO_xxx` Also there was code I replaced that was structured similarly.

2025-01-05 14:22 UTC, botovq commented on crypto/asn1/tasn_utl.c
>          REF_ASSERT_ISNT(ret < 0);
No offense intended :)

And I'm pretty sure at that point you alrady needed more than one committer to get something into the tree.

2025-01-05 14:22 UTC, botovq commented on include/openssl/configuration.h.in
> +# ifdef OPENSSL_NO_TLS1_3
I also meant to say that I'm not sure why you switched the order.

2025-01-05 19:26 UTC, richsalz commented on crypto/asn1/tasn_utl.c
>          REF_ASSERT_ISNT(ret < 0);
Absolutely non taken.

2025-01-05 19:27 UTC, richsalz commented on include/openssl/configuration.h.in
> +# ifdef OPENSSL_NO_TLS1_3
You can't do `no-tls1_3`. And I probably got the double-negative wrong more than once.

2025-01-05 19:31 UTC, richsalz commented on include/openssl/configuration.h.in
> +# ifdef OPENSSL_NO_TLS1_3
And I think your suggestion here is wrong.

2025-01-05 19:32 UTC, richsalz commented on util/check-format.pl
> +            report("code after '}'") unless $tail eq "" || $tail =~ m/(else|while|$)/;
LGTM.

2025-01-05 19:36 UTC, botovq commented on include/openssl/configuration.h.in
> +# ifdef OPENSSL_NO_TLS1_3
Right. I missed the #undef.

2025-01-05 19:39 UTC, botovq commented on include/openssl/configuration.h.in
> +# ifdef OPENSSL_NO_TLS1_3
Actually, how about moving the ones like `OPENSSL_NO_TLS1_3` into a separate block? I think going both ways in one single block is error prone and makes it super easy to make the mistake I made.

2025-01-05 19:41 UTC, richsalz commented on include/openssl/configuration.h.in
> +# ifdef OPENSSL_NO_TLS1_3
That's a good idea.  I made the same mistake :). I will do it in this PR

2025-01-05 20:09 UTC, richsalz commented on crypto/provider_conf.c
>  void ossl_provider_add_conf_module(void)
I'm worried that it will achieve sentience :)

2025-01-05 21:28 UTC, richsalz commented
Cygwin test failed in afalag, see test/afalgtest.c for details.  Fixup pushed.

2025-01-05 23:21 UTC, botovq requested changes
Still a couple of things and now the hmactest wants the same treatment as the afalg test.

2025-01-05 23:21 UTC, botovq commented on crypto/evp/p5_crpt2.c
This "fail open" `rv` can also go. Either `return EVP_KDF_derive(...) == 1;` at the end or
```C
if (EVP_KDF_derive(kctx, out, keylen, params) != 1)
    return 0;
return 1;
```

2025-01-05 23:21 UTC, botovq commented on crypto/pkcs12/p12_key.c
>          res = 1;
And please fix this to look the same as the one in p5_crpt2.c.

2025-01-05 23:21 UTC, botovq commented on util/check-format.pl
> +            report("code after '}'") unless $tail eq "" || $tail =~ m/(else|while|$)/;
Did you mean to change this or not? It seems to me that e.g. `elsewhere` now matches and previously it would not.

2025-01-06 00:49 UTC, richsalz commented on crypto/evp/p5_crpt2.c
moved the rv assignment since we need to free the context regardless.

2025-01-06 00:51 UTC, richsalz commented on util/check-format.pl
> +            report("code after '}'") unless $tail eq "" || $tail =~ m/(else|while|$)/;
oops. didn't write out the buffer...

2025-01-06 00:53 UTC, richsalz commented
>  now the hmactest wants the same treatment as the afalg test.

I wonder if something changed in the Cygwin platform, since many PRs are failing.  Oh well.  I'll make the same change to hmactest and then rebase later.

2025-01-06 06:39 UTC, botovq requested changes
Unsure. Could be a compiler update in the test runners. We've had complaints about such warnings for a long time, though.

Still a few very minor things.

2025-01-06 06:39 UTC, botovq commented on crypto/evp/p5_crpt2.c
Bah. Sorry.

2025-01-06 06:39 UTC, botovq commented on crypto/evp/p5_crpt2.c
> +    int rv =EVP_KDF_derive(kctx, out, keylen, params) == 1;
```suggestion
    int rv = EVP_KDF_derive(kctx, out, keylen, params) == 1;
```

2025-01-06 06:39 UTC, botovq commented on crypto/evp/p5_crpt2.c
> +    int rv =EVP_KDF_derive(kctx, out, keylen, params) == 1;
And while you're there, maybe call this `ret` instead of `rv` (same in PKCS12)?

2025-01-06 06:39 UTC, botovq commented on test/hmactest.c
> +        0x0b, 0x0b, 0x0b, 0x0b, 0x0b, 0x0b, 0x0b, 0x0b }, 16,
I think this would look more like the other entries:
```suggestion
    {
        {
            0x0b, 0x0b, 0x0b, 0x0b, 0x0b, 0x0b, 0x0b, 0x0b,
            0x0b, 0x0b, 0x0b, 0x0b, 0x0b, 0x0b, 0x0b, 0x0b
        }, 16,
```

2025-01-06 06:39 UTC, botovq commented on test/hmactest.c
> +        0xaa, 0xaa, 0xaa, 0xaa, 0xaa, 0xaa, 0xaa, 0xaa }, 16,
same here:
```suggestion
    {
        {
            0xaa, 0xaa, 0xaa, 0xaa, 0xaa, 0xaa, 0xaa, 0xaa,
            0xaa, 0xaa, 0xaa, 0xaa, 0xaa, 0xaa, 0xaa, 0xaa
        }, 16,
```

2025-01-06 06:39 UTC, botovq commented on util/check-format.pl
> +            report("code after '}'") unless $tail eq "" || $tail =~ m/(else|while|(\W|$)/;
```suggestion
            report("code after '}'") unless $tail eq "" || $tail =~ m/(else|while)(\W|$)/;
```

2025-01-06 15:46 UTC, botovq submitted a review, later dismissed
Alright. Looks good now.

Spotted two small nits while skimming through. Feel free to ignore. As mentioned, I didn't really review the apps part - it looks fine.

2025-01-06 16:01 UTC, richsalz commented
I took your two suggestsions, which are just whitespace changes, so if you want to approve I'll wait for the CI's to finish and merge later today (my day)

2025-01-06 16:08 UTC, botovq approved these changes

2025-01-06 19:28 UTC, merged