Add sslkeylog
quictls/quictls pull request #185
Opened 2024-12-29 01:52 UTC by richsalz

This adds the "sslkeylog" option.  By default its off, but I turned it on in Configure because builds break and I can't figure out why.

## Checklist
Thank you for your contribution. Please answer the following:

- [X] I acknowledge that I am authorized to submit this code under
the terms of the [Apache License](https://www.apache.org/licenses/LICENSE-2.0)
- [ ] All new public APIs are documented
- [ ] All new public functions have tests
- [ ] All new public functions have fuzzing tests

2025-01-02 23:34 UTC, botovq reviewed
A couple of comments. I would first try to get the ifdef right without making the callback configurable. Once that works you can revisit it. The logic is a bit tangly.

2025-01-02 23:34 UTC, botovq commented on Configure
> +    "sslkeylog-cb",
The entries aren't in alphabetic order (these two should go after `ssl-trace`.

2025-01-02 23:34 UTC, botovq commented on ssl/ssl_lib.c
> +     ERR_raise_data(ERR_LIB_SSL, ERR_R_INTERNAL_ERROR,
```suggestion
    ERR_raise_data(ERR_LIB_SSL, ERR_R_INTERNAL_ERROR,
```

2025-01-02 23:34 UTC, botovq commented on ssl/ssl_lib.c
> +#endif
I think the logic you have in the setter is enough to neuter the keylog callback entirely. You just don't ever set it, so you can leave it hanging as `NULL` off the `SSL_CTX`.

2025-01-02 23:34 UTC, botovq commented on ssl/ssl_lib.c
> +#if !defined(OPENSSL_NO_SSLKEYLOG_CB) && !defined(OPENSSL_NO_SSLKEYLOG)
This isn't right. `nss_keylog_int()` (what a stupid name) is called from `ssl_log_secret()` if only enable-keylog is given.

I'd suggest dropping this line. Otherwise you need || and the ifdefs below become hairy.

2025-01-02 23:34 UTC, botovq commented on ssl/ssl_lib.c
> +        do_sslkeylog(SSL_CONNECTION_GET_SSL(sc), (const char *)out);
Guard this:
```C
#if !defined(OPENSSL_NO_SSLKEYLOG)
    if (sctx->do_sslkeylog)
        do_sslkeylog(SSL_CONNECTION_GET_SSL(sc), (const char *)out);
#endif
```

2025-01-02 23:34 UTC, botovq commented on ssl/ssl_lib.c
> +    if (sctx->keylog_callback)
```suggestion
    if (sctx->keylog_callback != NULL)
```

2025-01-02 23:34 UTC, botovq commented on ssl/ssl_lib.c
>          return 1;
Then you can use the same logic as upstream:

```C
#if !defined(OPENSSL_NO_SSLKEYLOG)
    if (sctx->keylog_callback == NULL && sctx->do_sslkeylog == 0)
        return 1;
#else
    if (sctx->keylog_callback == NULL)
        return 1;
#endif

2025-01-02 23:34 UTC, botovq commented on ssl/ssl_lib.c
> +#endif
`ssl_log_rsa_client_key_exchange()` is called unconditionally in `tls_construct_cke_rsa()`, so this must return 1. However, I think you can just drop the OPENSSL_NO_SSLKEYLOG here.

2025-01-02 23:34 UTC, botovq commented on ssl/ssl_lib.c
> +    return 0;
Similarly here. This needs to return 1, otherwise you break `tls_construct_finished()`
and `quic_change_cipher_state()`. Easier to drop the #ifdefery.

2025-01-02 23:38 UTC, botovq commented on ssl/ssl_local.h
> +# ifndef OPENSSL_NO_SSLKEYLOG_CB
and of course you'd also drop this for now.

2025-01-02 23:45 UTC, botovq commented on ssl/ssl_lib.c
> +        OSSL_TRACE(TLS, "Unable to initalize keylog data\n");
I forgot: this also needs rethinking once OSSL_TRACE goes away.

2025-01-03 00:52 UTC, richsalz commented on ssl/ssl_lib.c
> +        OSSL_TRACE(TLS, "Unable to initalize keylog data\n");
Yeah, all those TRACE messages need to be handled.

2025-01-03 00:57 UTC, richsalz commented
So, I made the changes you suggest and the sslapi test fails, because of https://github.com/quictls/quictls/blob/main/test/sslapitest.c#L456-L472. Seems to me the choices are
- Enable sslapi-cb by default
- Remove the test
- Edit the test and pass a flag so we do it at runtime.
I'm inclined to do the last one; thoughts?

2025-01-03 05:42 UTC, botovq commented
I'm not sure I understand option 3. All this cannot succeed if you don't set the callbacks (i.e., I think the test should be wrapped into OPENSSL_NO_SSLKEYLOG_CB).

2025-01-03 14:34 UTC, richsalz commented
*   I’m not sure I understand option 3

In the light of day, I’m not sure Io do either :). I don’t know why I didn’t think of `#ifdef` in test source files…

2025-01-03 20:10 UTC, botovq reviewed
Almost there...

https://github.com/quictls/quictls/blob/21e4ce9ca8041cd726b80f2e9f2db5792a2eefd4/test/sslapitest.c#L101-L106

needs to be guarded by something like
```C
#if !defined(OPENSSL_NO_KEYLOG_CB) || !defined(OPENSSL_NO_TLS_1_2) || defined(OSSL_NO_USABLE_TLS1_3) || !defined(OPENSSL_NO_BORING_QUIC_API)
```

2025-01-03 20:10 UTC, botovq commented on test/sslapitest.c
> +#if !defined( OSSL_NO_USABLE_TLS1_3) && !defined(OPENSSL_NO_SSLKEYLOG)
```suggestion
#if !defined(OSSL_NO_USABLE_TLS1_3) && !defined(OPENSSL_NO_SSLKEYLOG_CB)
```

2025-01-03 20:17 UTC, richsalz commented on doc/man3/SSL_CTX_set_keylog_callback.pod
> +functions do nothing.
fixed that.

2025-01-03 20:22 UTC, richsalz commented on doc/man3/SSL_CTX_set_keylog_callback.pod
>  the value of cb, no logging of key material will be done.
They're going to fix it, I think, since I reported the issue.

2025-01-03 20:41 UTC, botovq commented on test/sslapitest.c
> +#if !defined(OPENSSL_NO_SSLKEYLOG_CB)
This might happen to work in CI, but I don't think it is correct. The variables are also used in blocks guarded by the three other conditions I listed.

2025-01-03 20:43 UTC, richsalz commented on test/sslapitest.c
> +#if !defined(OPENSSL_NO_SSLKEYLOG_CB)
:). I turned the. cut and paste (dang, even the comment!) into a function ...

2025-01-03 21:16 UTC, botovq reviewed
Stil a couple issues with the #ifdef mess in sslapitest. And the move of the safe_getenv caused some breakage, too. Shouldn't be all that hard to fix.

I unresolved a couple of things and added a couple more notes.

2025-01-03 21:16 UTC, botovq commented on include/openssl/conf.h.in
> +char *ossl_safe_getenv(const char *);
I always liked how this uses OPENSSL_issetugid() which is a direct wrapper of issetugid() where available, which has a couple of issues very relevant to the present use that Nico Williams summarized in [this lovely gist](https://gist.github.com/nicowilliams/4daf74a3a0c86848d3cbd9d0cdb5e26e)...

2025-01-03 22:37 UTC, richsalz commented on doc/man3/SSL_CTX_set_keylog_callback.pod
> +functions do nothing.
double-checked, yes.  (maybe I didn't push before?)

2025-01-03 22:38 UTC, richsalz commented on doc/man3/SSL_CTX_set_keylog_callback.pod
>  the value of cb, no logging of key material will be done.
you're right, added text to clarify.

2025-01-03 22:45 UTC, richsalz commented on include/openssl/conf.h.in
> +char *ossl_safe_getenv(const char *);
Oh, my.  I'm going to add a couple of sentences to doc/ma7/openssl-env

2025-01-04 07:57 UTC, botovq reviewed
ossl_safe_getenv() does not belong into a public header. Perhaps include/internal/common.h?


I don't know how you added the commits from main to this branch (cherry-pick?). Please stop doing this, it is very confusing. The github review interface adds them to the diff view (which now contains 43 files with +670 -1554 lines).

I would prefer a rebase on top of main and force-push or using a merge commit if need be.

2025-01-04 07:57 UTC, botovq commented on test/sslapitest.c
> +    clean_log_space();
clean_log_space() needs to be outside of OPENSSL_NO_SSLKEYLOG_CB

2025-01-04 07:57 UTC, botovq commented on include/openssl/conf.h.in
> +char *ossl_safe_getenv(const char *);
Oh, and surely this doesn't belong into a public header.

2025-01-04 15:30 UTC, richsalz commented
> Oh, and surely this doesn't belong into a public header.

I know, right?  The problem is that the function has to be exported from libcrypto so that libssl can use it.  Looking at the `CRYPTOHEADERS` variable, I will try to move it to include/internal/sslconf.h

Sorry about the merge/rebase/screwup.  Git is sometimes way beyond me.  I'll do a clean rebase and force-push shortly.

2025-01-04 15:44 UTC, botovq commented
You can prototype `ossl_safe_getenv()` as many times as you want, but openssl gets away with protyping it only in `internal/cryptlib.h`. This is included from ssl_lib.c. Surely having a function in a header or not isn't going to determine if a function is exported or not (that said, I never looked at how OpenSSL exports symbols, I'm not sure I want to).

2025-01-04 17:38 UTC, richsalz commented
addressed issues, compiled clean, rebased and pushed.

2025-01-04 17:39 UTC, botovq commented
Ah, much better. Thanks :) I'll look soon.

2025-01-04 17:40 UTC, richsalz commented
>  (that said, I never looked at how OpenSSL exports symbols, I'm not sure I want to).

you don't want to.  It is, as you might guess, done via a hackage of perl building util/libcrypto.num (and others).  I don't fully understand it. Maybe with VMS gone it can get simpler; I'll look into it sometime.

2025-01-04 17:51 UTC, botovq commented
I really don't think we want to export openssl_safe_getenv() from libcrypto, so please revert the libcrypto.num addition. Including sslconf.h in libcrypto also feels very wrong. I think having the one prototype in cryptlib.h should be good enough. (If it's also needed in sslconf.h we can just add it there. There's nothing wrong with that, but let's not if we can help it).

I believe openssl makes this work by linking getenv.c into both libssl and libcrypto, via [SHARED_SOURCE in quic/build.info][1]. This obviously fell victim to the QUIC purge...

[1]: https://github.com/openssl/openssl/blob/817a2b2b4955da0233fe7e6e4bd16c0255262b4f/ssl/quic/build.info#L23

2025-01-04 18:01 UTC, richsalz commented
If it's not in libcrypto, then libssl can't use it.  *only* functions named in libcrypto are available.

2025-01-04 18:01 UTC, botovq commented
It is in both since the .c file is compiled into both libraries.

2025-01-04 18:08 UTC, richsalz commented
Okay, I will add it to libssl, thanks.

2025-01-04 18:23 UTC, richsalz commented
fixup commit pushed.

2025-01-04 19:32 UTC, richsalz commented
I fixed the two failing checks.

2025-01-04 20:49 UTC, botovq requested changes
Alright. All that's left are two tiny nits.

So much effort for this. Quite frankly, I think this functionality is a terrible idea, but more and more people expect to have it, unfortunately. LibreSSL will push back against this as long as we can.

2025-01-04 20:49 UTC, botovq commented on ssl/build.info
> +# For shared builds we need to some othe files in libssl
```suggestion
# For shared builds we need to include some of the files in libssl.
```

2025-01-04 20:49 UTC, botovq commented on ssl/build.info
> +        ../crypto/packet.c ../crypto/time.c ../crypto/getenv.c
```suggestion
        ../crypto/getenv.c ../crypto/packet.c ../crypto/time.c
```
let's keep these sorted.

2025-01-04 20:49 UTC, botovq commented on ssl/ssl_lib.c
> +        OSSL_TRACE(TLS, "Unable to initalize keylog data\n");
Let's deal with this in the no-trace PR.

2025-01-04 20:49 UTC, botovq commented on ssl/ssl_lib.c
I think there's some room for improvement of the code that already was in here...

2025-01-04 20:52 UTC, richsalz commented
So much effort for a security hole :)

>LibreSSL will push back against this as long as we can.

Be brave!

I took your two commit suggestions.

2025-01-04 20:53 UTC, botovq approved these changes

2025-01-04 20:55 UTC, botovq commented
Fortunately we have this reputation of being abrasive *expletive elided* - that makes it easier :)

Phew. Looks like we're done. I'd like to see this completely green before we merge.

2025-01-05 07:31 UTC, merged