Document RSA-PSS DER output change
quictls/quictls pull request #188
Opened 2024-12-31 16:54 UTC by richsalz

A fix to https://github.com/openssl/openssl/issues/20088 which I have shared with them.

## Checklist
Thank you for your contribution. Please answer the following:

- [X] I acknowledge that I am authorized to submit this code under
the terms of the [Apache License](https://www.apache.org/licenses/LICENSE-2.0)
- [ ] All new public APIs are documented
- [ ] All new public functions have tests
- [ ] All new public functions have fuzzing tests

2024-12-31 17:52 UTC, botovq commented
This is a mess that goes back much further, see e.g. this note from RFC 5754, which is explicitly about SHA-2 (a very similar note i also in RFC 4055):

>   NOTE: There are two possible encodings for the AlgorithmIdentifier
   parameters field associated with these object identifiers.  The two
   alternatives arise from the loss of the OPTIONAL associated with the
   algorithm identifier parameters when the 1988 syntax for
   AlgorithmIdentifier was translated into the 1997 syntax.  Later, the
   OPTIONAL was recovered via a defect report, but by then many people
   thought that algorithm parameters were mandatory.  Because of this
   history, some implementations encode parameters as a NULL element
   while others omit them entirely.  The correct encoding is to omit the
   parameters field; however, when some uses of these algorithms were
   defined, it was done using the NULL parameters rather than absent
   parameters.  For example, PKCS#1 [[RFC3447](https://www.rfc-editor.org/rfc/rfc3447)] requires that the padding
   used for RSA signatures (EMSA-PKCS1-v1_5) MUST use SHA2
   AlgorithmIdentifiers with NULL parameters (to clarify, the
   requirement "MUST generate SHA2 AlgorithmIdentifiers with absent
   parameters" in the previous paragraph does not apply to this
   padding).

RFC 4055 and 8017 both require explicit NULL encoding rather than the encoding that OpenSSL 1.1 used, so the change in OpenSSL seems correct to me and the old documentation was just incorrect (as it quite often is).

Incidentally, that is also the reason for the existence of `EVP_MD_FLAG_DIGALGID_NULL` and
`EVP_MD_FLAG_DIGALGID_ABSENT`, but of course the intention was lost somewhere and the former was, to my knowledge, never actually used.

[1]: https://www.rfc-editor.org/rfc/rfc5754#page-4

2024-12-31 18:32 UTC, richsalz commented
We ran into this undocumented change -- which I agree is now correct -- when a customer was using the old encoding and we stopped working during an OpenSSL upgrade. If you look at the fix you can see some of our investigation.

There's reasons why the IETF doesn't like parameters included as part of algorithms any more, and this is one of them. ;)

2024-12-31 19:11 UTC, botovq requested changes
When I read the diff here first, I was confused because I couldn't recall RFC 5280 actually saying anything about algorithm parameters (and it really doesn't, it only refers to other RFCs, like 4055, among others).

With the reference changed from RFC 4055 to RFC 8017 (which for some reason no longer explains this detail) the chance of finding out the *why* of this weird encoding seems to become even slimmer.

I guess my suggestion is to be slightly more explicit and include a reference to RFC 4055, section 2.1.

2024-12-31 19:11 UTC, botovq commented on doc/man7/RSA-PSS.pod
> +RFC 5280, by outputting two extra NULL values (for optional
```suggestion
RFC 5280, by including two extra NULL values (for optional
```

2024-12-31 19:11 UTC, botovq commented on doc/man7/RSA-PSS.pod
> +while 3.0 and later used RFC 8017.
```suggestion
while 3.0 and later use RFC 8017.
```

2025-01-01 10:39 UTC, botovq commented on doc/man7/RSA-PSS.pod
> +L<section 3.1|https://www.rfc-editor.org/rfc/rfc4055.html#section-3.1>
That's not right: both RFCs require the explicit ASN.1 NULL to be there. It is the documentation that was incorrect in claiming that the old format corresponds to RFC 4055.

2025-01-01 10:39 UTC, botovq commented on doc/man7/RSA-PSS.pod
> +by outputting two extra NULL values (for optional
The reason I suggested changing this to 'including' previously is that I dislike 'output' here. It feels imprecise: the format doesn't output anything.

2025-01-01 16:13 UTC, richsalz commented
Pushed a fixup commit that hopefully gets the language right.

2025-01-01 16:22 UTC, botovq requested changes
Two typos, with those fixed, I think it's good.
(technically OpenSSL didn't claim to conform to that particular subsection, but I think it's better to have a precise reference rather than an entire 24-page document)

2025-01-01 16:22 UTC, botovq commented on doc/man7/RSA-PSS.pod
> +OpenSSL release 1.1 and earlier claimed to confirm to
```suggestion
OpenSSL release 1.1 and earlier claimed to conform to
```

2025-01-01 16:22 UTC, botovq commented on doc/man7/RSA-PSS.pod
> +Starting with OpenSSL releaes 3.0 the output was conformant with RFC 8017.
```suggestion
Starting with OpenSSL release 3.0 the output was conformant with RFC 8017.
```

2025-01-01 16:46 UTC, richsalz commented
merged your suggestions, needs re-approval thanks.

2025-01-01 16:48 UTC, botovq approved these changes

2025-01-01 16:51 UTC, merged