Move more common macros to common.h
quictls/quictls pull request #190
Opened 2024-12-31 21:26 UTC by richsalz

An old cleanup that the other guys aren't going to do :)

## Checklist
Thank you for your contribution. Please answer the following:

- [X] I acknowledge that I am authorized to submit this code under
the terms of the [Apache License](https://www.apache.org/licenses/LICENSE-2.0)
- [ ] All new public APIs are documented
- [ ] All new public functions have tests
- [ ] All new public functions have fuzzing tests

2025-01-01 13:07 UTC, botovq reviewed
A few small things should be addressed.

2025-01-01 13:07 UTC, botovq commented on crypto/bf/bf_local.h
>  # define n2ln(c,l1,l2,n) { \
This one and the ones below should also go, no? They aren't guarded, so there's a redefinition here.

2025-01-01 13:07 UTC, botovq commented on include/internal/common.h
> +                        case 8: l2 =((unsigned long)(*(--(c))))    ; \
This is still using icky old eay style spacing and parentheses.

2025-01-01 17:25 UTC, richsalz commented on include/internal/common.h
> +                        case 8: l2 =((unsigned long)(*(--(c))))    ; \
additional commit pushed.  I wonder if these should become `static inline` functions?

2025-01-01 17:51 UTC, botovq commented
The `-Wimplicit-fallthrough` breakage is fun. So to avoid that you have to obfuscate the Duff device by adding `/* fallthrough */` comments. Gotta love compiler warnings :)

> I wonder if these should become static inline functions?

I'm not sure. At least this way the signatures would make the advancing and other side effects explicit... These macros are so nasty.

There's a bunch more of them in ct_local.h, rc2_local.h, rc5_local.h

2025-01-01 17:58 UTC, botovq commented on include/internal/common.h
> + * to get a "sequence point" to insure that the right bytes
```suggestion
 * to get a "sequence point" to ensure that the right bytes
```

2025-01-01 17:58 UTC, botovq commented on include/internal/common.h
> +            || (path[0] != '\0' && path[1] == ':'))
This could just go on asingle line, no? Also, I don't know much about Windows but can really any non-NUL character be used here?

2025-01-01 17:58 UTC, botovq commented on include/internal/common.h
> +        case 8: l2  = ((unsigned long)(*(--(c)))) << 24; \
Apparently the fallthrough comments need to stay here and in all the other switches.

2025-01-01 21:04 UTC, richsalz commented on include/internal/common.h
> +            || (path[0] != '\0' && path[1] == ':'))
Well, any letter is okay (network drives via `net use` command can pick a letter).  But if someone enters `?:\foo.conf` as a config file, then they get whatever they desrve; not worth the `isupper` check.

2025-01-01 21:05 UTC, richsalz commented on include/internal/common.h
> +        case 8: l2  = ((unsigned long)(*(--(c)))) << 24; \
oops.  I added rc2,rc5 to my builds.

2025-01-01 21:14 UTC, richsalz commented
Pushed a fixup with your spelling fix, the one-liner (commented), /* fallthrough */, and {ct,rc2,rc5}_local.h
Thanks for the careful review!

2025-01-01 21:35 UTC, botovq commented
It'll take a moment to review this in full. There's still the ones in des_local.h and mdc2dgst.c:

https://github.com/quictls/quictls/blob/964f201c941d016465c2c1bdfd1d9963caf62877/crypto/des/des_local.h#L29-L82

and

https://github.com/quictls/quictls/blob/964f201c941d016465c2c1bdfd1d9963caf62877/crypto/mdc2/mdc2dgst.c#L23-L34

2025-01-01 21:43 UTC, richsalz commented
Take your time, maybe wait until the builds clear 😊

2025-01-02 05:34 UTC, botovq requested changes
I think this will need one or two more iterations. What a mess.

2025-01-02 05:34 UTC, botovq commented on crypto/idea/idea_local.h
> -#define s2n(l,c)        (*((c)++)=(unsigned char)(((l)     )&0xff), \
Amazing. This one is different from all the other `s2n`. Fortunately, idea doesn't use this.

2025-01-02 05:34 UTC, botovq commented on include/internal/common.h
> +          (((unsigned long)((c)[2]))    )), \
The first two lines should have an extra space after `<<` and the third line then needs an extra space for alignment.

2025-01-02 05:34 UTC, botovq commented on include/internal/common.h
> +        l1 = l2 = 0; \
Missing parentheses in the previous two lines (and all the `l1` and `l2` below).

2025-01-02 05:34 UTC, botovq commented on include/internal/common.h
> +        c += n; \
```suggestion
        (c) += (n); \
```

2025-01-02 05:34 UTC, botovq commented on include/internal/common.h
> +        c += n; \
```suggestion
        (c) += (n); \
```

2025-01-02 05:34 UTC, botovq commented on include/internal/common.h
> +        switch (n) { \
```suggestion
        switch ((n)) { \
```

2025-01-02 15:02 UTC, richsalz commented on crypto/des/des_local.h
> -/* NOTE - c is not incremented as per c2l */
It took me awhile to figure that out.  It means "c is not incremented like c2l does it". But I will remove the comment.

2025-01-02 15:05 UTC, botovq commented on crypto/des/des_local.h
> -/* NOTE - c is not incremented as per c2l */
Ah good. Then it's not just me :)

2025-01-02 15:11 UTC, richsalz commented on include/internal/common.h
> +          (c) += 2)
`git grep n2s` shows that the value is never used.  I could make all of them have a `(void)` cast ...

2025-01-02 15:11 UTC, richsalz commented on include/internal/common.h
> +          (((unsigned long)((c)[2]))    )), \
fixed

2025-01-02 15:17 UTC, botovq commented on include/internal/common.h
> +          (c) += 2)
None of the values of these macros is ever used. However, I would prefer if there was only one or two idioms rather than more of them. So whichever version you prefer (array subscripts or the ++ version, please use it throughout, with the exception of the Duff devices).

2025-01-02 15:33 UTC, richsalz commented on include/internal/common.h
> +        l1 = l2 = 0; \
fixed

2025-01-02 15:41 UTC, richsalz commented
I totally agree about the importance of consistency and I’m converting all to use the `*c++` style.

2025-01-02 18:28 UTC, botovq submitted a review, later dismissed
I would prefer if all the l (and l1 and l2) were also guarded with parentheses, but I'm not going to insist.

2025-01-02 18:50 UTC, richsalz commented
I pushed a fixup to turn naked `l` into `(l)` in macro bodies.  I did not change the on-line macros that call the "XXX" equivalent to wrap things since we "know" the XXX versions do it.

2025-01-02 18:59 UTC, botovq commented
From this I understand you meant to do these two as well:

https://github.com/quictls/quictls/blob/97de51b13ab48ca2208342f6cadb742912b6e394/include/internal/common.h#L169-L188

and

https://github.com/quictls/quictls/blob/97de51b13ab48ca2208342f6cadb742912b6e394/include/internal/common.h#L215-L235

2025-01-02 19:02 UTC, richsalz commented
Oops, didn’t save that set of changes before building and commiting.  Doing it now.

2025-01-02 19:07 UTC, botovq approved these changes
Looks good now. Let's let the CI complete before merging this.

2025-01-03 05:47 UTC, merged